name: recipes.jacobpledger.ca
description: Jacob Pledger's Tasty Food

collections:
  recipes:
    output: true
collections_dir: "collections"

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
